defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['POSTGRES_USERNAME'] || ENV['USER'] %>

development:
  database: project_list_development
  <<: *defaults

test:
  database: project_list_test
  min_messages: WARNING
  <<: *defaults

staging:
  database: project_list_staging
  <<: *defaults

production:
  database: project_list_production
  <<: *defaults
  url: <%= ENV['DATABASE_URL'] %>