island94:
  name: "Island 94"
  url: "https://island94.org"
  description: |
    A blog and commonplace book.
dayoftheshirt:
  name: "Day of the Shirt"
  url: "https://dayoftheshirt.com"
  description: |
    Daily t-shirt sales from 30+ websites in one place.
panlexicon:
  name: "Panlexicon"
  url: "https://panlexicon.com"
  description: |
    A unique thesaurus for writing and English exploration.
open311status:
  name: "Open311 Status"
  url: "https://status.open311.org"
  wait_for_assets_to_load: false
  description: |
    Monitors and aggregates the status of dozens of Open311 API endpoints, providing benchmarks and comparative insights.
americancommissar:
  name: "American Commissar"
  url: "https://americancommissar.wordpress.com/"
  description: |
    Digitization of my grandfather's memoir about labor organizing and serving the Spanish Civil War.
printandshare:
  name: "Print and Share"
  url: "http://printandshare.org"
  description: |
    Easily create beautiful & printable handouts to advertise your DonorsChoose projects.
civictechpatterns:
  name: "Civic Tech Patterns"
  url: "https://github.com/codeforamerica/civic-tech-patterns"
  description: |
    A collection of patterns and anti-patterns for describing common practices in Civic Technology.
brompt:
  name: "Brompt"
  url: "https://brompt.com"
  description: |
    The intelligent accountability partner that helps you become a better writer.
dayofthesock:
  name: "Day of the Sock"
  url: "https://dayofthesock.com"
  description: |
    We collect the best socks and share them so you can stay on top of your sock game.
sheldoncalderon:
  name: "Sheldon Calderon"
  url: "http://sheldoncalderon.com"
  description: |
    Our family website.
sflc:
  name: "Saint Francis Lutheran Church"
  url: "http://sflcsf.org/"
  description: |
    An ELCA church in San Francisco's Castro where I am a member.
projectlist:
  name: "Project List"
  url: "https://projects.island94.org"
  description: |
    A list of Ben's projects.
