island94:
  url: "https://island94.org"
dayoftheshirt:
  url: "https://dayoftheshirt.com"
panlexicon:
  url: "https://panlexicon.com"
project_list:
  url: "https://bensheldon-projectlist.herokuapp.com"
printandshare:
  url: "http://printandshare.org/"